---
# tasks file for webserver
- name: Install apache
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - httpd
    - mod_ssl

- name: Configure a VirtualHost
  template:
    src: etc/httpd/conf.d/ansibletest.conf
    dest: /etc/httpd/conf.d/ansibletest.conf
  notify: apache restart

- name: Ensure apache is running
  service:
    name: httpd
    state: started
    enabled: yes
